sudo: false

language: python
python:
- 3.3
- 3.4
- 3.5

cache: pip

env:
  global:
  - RANDOM_SEED=12345

install:
- pip install coveralls scrutinizer-ocular

before_script:
- make env
- make depends-ci
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start

script:
- make ci

after_success:
- coveralls
- ocular

notifications:
  email:
    on_success: never
    on_failure: change
